version: "2.1"
services:
  lofka:
    image: tsingjyujing/lofka-lite
    restart: "always"
    ports:
      - "9500:9500"
    depends_on:
      - mongo

  mongo:
    image: mongo:4-xenial
    restart: "always"
    healthcheck:
      test: "echo 'db.stats().ok' | mongo 127.0.0.1:27017/leanote --quiet"
    volumes:
      - "~/app/lofka/data:/data/db"
    mem_limit: 800M